server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  service-url:
    defaultZone: http://yangjn:123456@localhost:8761/eureka/

spring:
  security:
    user:
      name: yangjn
      password: 123456
      roles: SUPERUSER

logging:
  config: classpath:logback.xml

