server:
  port: 7201

eureka:
  client:
    service-url:
      defaultZone: http://yangjn:123456@localhost:8761/eureka/

spring:
  application:
    name: hello-service-consumer



logging:
  config: classpath:logback.xml

