server:
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://yangjn:123456@localhost:8761/eureka/

mybatis-plus:
  mapper-locations: classpath*:com/mooc/meetingfilm/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:mooc_meetingfilm}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:123456}
    filters: log4j,wall,mergeStat


logging:
  config: classpath:logback.xml